// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamotest",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "testapi",
            "endpoint": "https://i667omprzj.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:593d52ae-0e06-4627-acde-2f77873aae2c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_c6P2ZVC6M",
    "aws_user_pools_web_client_id": "4ri1refqbfoev6an37h19onb9j"
};


export default awsmobile;
